export { default as MainPage } from './MainPage'
export { default as ResumePage } from './ResumePage'
export { default as FAQPage } from './FAQPage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as WorkPage } from './WorkPage'
export { default as WorkAtMtsPage } from './WorkAtMtsPage'
export { default as RulesPage } from './RulesPage'
